import { AUTH_ROUTES, TASK_ROUTES } from './routes';

const AUTH_API_URL = import.meta.env.VITE_AUTH_API_URL;
const TASK_API_URL = import.meta.env.VITE_TASK_API_URL;

export const ENDPOINTS = {
  // Auth endpoints
  AUTH_LOGIN: `${AUTH_API_URL}${AUTH_ROUTES.LOGIN}`,
  AUTH_REGISTER: `${AUTH_API_URL}${AUTH_ROUTES.REGISTER}`,
  AUTH_VERIFY: `${AUTH_API_URL}${AUTH_ROUTES.VERIFY}`,
  AUTH_FORGOT_PASSWORD: `${AUTH_API_URL}${AUTH_ROUTES.FORGOT_PASSWORD}`,
  AUTH_RESET_PASSWORD: `${AUTH_API_URL}${AUTH_ROUTES.RESET_PASSWORD}`,
  
  // Task endpoints
  TASK_CREATE: `${TASK_API_URL}${TASK_ROUTES.CREATE}`,
  TASK_UPDATE: `${TASK_API_URL}${TASK_ROUTES.UPDATE}`,
  TASK_DELETE: `${TASK_API_URL}${TASK_ROUTES.DELETE}`,
  TASK_GET: `${TASK_API_URL}${TASK_ROUTES.GET_ALL}`,
  TASK_GET_ONE: `${TASK_API_URL}${TASK_ROUTES.GET_ONE}`,
  TASK_COMPLETE: `${TASK_API_URL}${TASK_ROUTES.COMPLETE}`,
  TASK_INCOMPLETE: `${TASK_API_URL}${TASK_ROUTES.INCOMPLETE}`,
  TASK_BY_PRIORITY: `${TASK_API_URL}${TASK_ROUTES.BY_PRIORITY}`,
  TASK_BY_DUE_DATE: `${TASK_API_URL}${TASK_ROUTES.BY_DUE_DATE}`
};